### ISSUE TITLE
Does this work with the new apollo client v3.0

### ISSUE THREAD

**Issue by hannojg** [Mike-Gibson/mock-apollo-client#11]
Hey, Apollo Client v3.0 is in beta, and I was wondering whether this library is compatible with it? 

Thank you in advance for your response 😊

**Comment by Mike-Gibson** [comment]
I've just had a look at the breaking changes - they are quite significant.

I'm not sure about functional breaking changes which may stop mock-apollo-client from working, but there's at least a fundamental change to the package name - it's now `@apollo/client` rather than `apollo-client`. Mock-apollo-client has a peer dependency on `apollo-client`, so it won't work with 3.0 as it stands.

I'll have to have a think about how mock-apollo-client could/should change - whether it should try and support both v2 and v3 of Apollo client, or whether to drop support for v2 going forwards. I'll try and take a look at some other libraries that face similar problems.

Thanks for asking the question! I'm not actively working on a project using Apollo client at the moment, so wasn't aware of the upcoming version 3 of Apollo client. I'm open to any suggestions/ideas you may have on the above.

**Comment by joshuatvernon** [comment]
It might be worth adding a disclaimer on the `README.md` in the meantime. I just set everything up and was very puzzled as to why it wasn't working and would have saved some time if I had known.

Thanks though, this library seems really useful if you can use it!

**Comment by Mike-Gibson** [comment]
@joshuatvernon thanks - very good suggestion. I've added a note at the top of the README.

**Comment by memark** [comment]
Any update on this? What are your thoughts so far, @Mike-Gibson?

Granted there is a `<MockedProvider />` in Apollo v3, but it only works for react components, not with the bare apollo client, AFAIK.

**Comment by Mike-Gibson** [comment]
Hi @memark , thanks for your interest.

I haven't been using Apollo client recently and the Apollo client 3 release went completely under my radar. 

I'll take another look at it, hopefully this week sometime. I had it hanging together with the Apollo 3 release candidate I think but need to double check things haven't changed since.

I think I will keep v0.x for Apollo client 2 and bump the version to v1.x for Apollo client 3.

Stay tuned!

**Comment by Mike-Gibson** [comment]
@hannojg, @memark I have just published v1.0.0 of mock-apollo-client which supports Apollo client 3.

If you're able to, I would be grateful if you could give it a go and let me know if you run into any issues.

Thanks.
