### ISSUE TITLE
How can I make a setRequestHandler, for the same query, have multiple different promise results or use a paramter?

### ISSUE THREAD

**Issue by davidcolatti** [Mike-Gibson/mock-apollo-client#18]

**Comment by Mike-Gibson** [comment]
Hi,

There are a couple of ways when using Jest, which have been mentioned in https://github.com/Mike-Gibson/mock-apollo-client/issues/10:

1: Configure the responses for a set order:
```typescript
const requestHandler = jest.fn();
requestHandler.mockResolvedValueOnce({ data:  { dog: { id: 1, name: 'Rufus', breed: 'Poodle' } } });
requestHandler.mockResolvedValueOnce({ data:  { dog: { id: 2, name: 'Fred', breed: 'Terrier' } } });

mockClient.setRequestHandler(GET_DOG_QUERY, requestHandler);
```

This has the downside that if there are two requests in parallel you can't guarentee which is resolved first

2: Use a library like [jest-when](https://www.npmjs.com/package/jest-when) which would allow you to set up the request handler to return a specific response based on the query parameters rather than just relying on the order in which the queries are called.

You could also probably do this yourself with something like (warning: I haven't tried this code!)

```typescript
const queryHandler = jest.fn((parameters) => parameters.name === 'Rufus'
  ? Promise.resolve({ data: { dog: { id: 1, name: 'Rufus', breed: 'Poodle' } } })
  : Promise.resolve({ data: { dog: { id: 2, name: 'Fred', breed: 'Terrier' } } }));
```

Hope that helps.

**Comment by davidcolatti** [comment]
You're awesome!! Thank you

**Comment by davidcolatti** [comment]
By the way, the ternary operators worked well!
